# Generated by Django 5.2.11 on 2026-03-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_alter_proveedor_nombre_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
