# Generated by Django 5.2.11 on 2026-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('contrasena_hasheada', models.CharField(max_length=100)),
                ('nombre_sucursal', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(blank=True, max_length=128, null=True)),
                ('rol', models.CharField(choices=[('admin_general', 'Admin General'), ('admin_sucursal', 'Admin Sucursal')], default='admin_sucursal', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
