# Generated by Django 5.2.11 on 2026-03-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_sucursal',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_general', 'Admin General'), ('admin_sucursal', 'Admin Sucursal')], default='admin_sucursal', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
