# Generated by Django 5.2.11 on 2026-03-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
        ('producto', '0002_categoriaproducto_producto_categoria'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='unique_producto_por_pedido'),
        ),
    ]
